create table trips
(
    id        bigint  not null primary key,
    cancelled boolean not null
);

create table users
(
    username varchar(255) not null primary key
);

create table bookings
(
    id            bigint generated by default as identity primary key,
    amount        integer      not null check (amount <= 2147483647 AND amount >= 1),
    cancelled     boolean      not null,
    trip_id       bigint       not null,
    user_username varchar(255) not null,

    constraint fk_bookings_trips foreign key (trip_id) references trips,
    constraint fk_bookings_users foreign key (user_username) references users
);