server:
  port: ${PORT:8080}

spring:
  application:
    name: ${TRIP_SERVICE_NAME:trip}
  resources:
    add-mappings: false
  mvc:
    throwExceptionIfNoHandlerFound: true

  # Database
  datasource:
    url: "jdbc:postgresql://${TRIP_DB_URL}/${TRIP_DB_NAME}"
    username: ${TRIP_DB_USERNAME}
    password: ${TRIP_DB_PASSWORD}
    driver-class-name: "org.postgresql.Driver"
  jpa:
    database: "postgresql"
    hibernate:
      ddl-auto: validate

  # Session
  session:
    store-type: redis
  redis:
    host: ${REDIS_URL}
    port: ${REDIS_PORT}

  # Message-Broker
  rabbitmq:
    host: ${RABBITMQ_URL}

  # Discovery
  cloud:
    consul:
      host: ${DISCOVERY_URL}
      port: ${DISCOVERY_PORT}
      discovery:
        instance-id: ${spring.application.name}:${random.value}
